### ISSUE TITLE
Friend Perms exploit

### ISSUE THREAD

**Issue by rickygwapo** [LlmDl/Towny#2419]
Hi, So there's a problem on the permissions on the server such as when a town has every single permissions off and residents can only build on their owned plots but the problem is that when those residents adds a friend with /resident friend add. Those friends can edit any of town's land even though the permissions are off which can lead a whole town being griefed even though the perms are configured correctly. I hope this issue can be fixed and thank you in advance.

**Comment by LlmDl** [comment]
Just tested this:

1. My town does not allow residents to alter any land they don't personally own.
2. Added Player B from outside the town to my friends list. 
3. Player B cannot break town-owned land.

Since I cannot reproduce this, I'll need you to show me the following:

1. A full startup from the latest.log
2. Your permission plugin's permission file.
3. The townyperms.yml.
 All on pastebin.com, and linked here.

**Comment by rickygwapo** [comment]
Town Permissions : http://pastebin.com/WMMArVwV
Permissions : http://pastebin.com/Rqbxcecf
Startup : http://pastebin.com/5jVSAin2

====

and i have another issue with towns not going to ruins even though their town bank is at 0$ and we have an upkeep of $15,000. I have about 3000towns existing on the server and about hundreds of those are at 0$ bank and whenever there's a new day come, only about 5 - 7towns going down. Is it possible that it has a limit on how many towns can go down. not really sure what's the problem.

towny config just in case : http://pastebin.com/S01Ek4EM

**Comment by LlmDl** [comment]
In your pex file: remove all towny nodes except for towny.wild.*, all of the correct nodes are already given out in the townyperms.yml. If this does not fix the problem, stop using PEX, we don't troubleshoot problems involving it.

As for anything else I cannot say what your issue is. We don't recommend using Essentials Eco as it has been resetting towny bank accounts lately and there is not plan from their developers to update/fix it.

**Comment by rickygwapo** [comment]
i see, alright thank you for your response.

**Comment by rickygwapo** [comment]
what economy do you recommend?

**Comment by LlmDl** [comment]
Vault and CraftConomy3 seems to be the way to go now.
