### ISSUE TITLE
Towny plot protection regen for explosions

### ISSUE THREAD

**Issue by wizrow** [LlmDl/Towny#2528]
Since towny has a regeneration for protected blocks (assuming its protected town plots), there is no regeneration for blocks from explosions when toggling explosives are enabled in the town. I'm not sure if this is a thing already, but I want to be able to regen protected plots after an explosion. I know that this explosion regen system works in the wilderness. Also toggling explosions off does not damage blocks at all. It would be great if someone could help me fix the issue or patch this in the next towny update.

**Comment by LlmDl** [comment]
This is now a thing when the war event is active as of 0.91.4.6. I don't see the point in putting in a regen when a mayor has already decided to disable explosions in their land. War is an exception since it's an avoidable thing (you can choose to have no nation or to pay for neutrality when wars are active.)
