### ISSUE TITLE
Suggestion: Have an option to prevent lava from flowing into a claimed area.

### ISSUE THREAD

**Issue by KarlOfDuty** [LlmDl/Towny#2556]
We are having trouble with people making giant cobble monsters that stretch into claimed areas, this could be prevented by either disabling lava flow from outside of a claimed area into one, like you have done with pistons. 

Another solution might be to disable cobblestone being created by lava touching water.

**Comment by LlmDl** [comment]
Blocking lava and water flows would be too much of a strain on most servers as those events would be fired and cancelled constantly until the lava source is removed/blocked from entering the town.

You can disable placing lava in the wilderness with the right permission node, though someone could still pour lava from an adjacent townblock (if you haven't made it so that Towns can claim close to claimed land.)

On my server I allow people to do w/e they want in the wilderess but if they mess with a town's borders like that it's a ban. You might want to just make a rule to deal with this.
