### ISSUE TITLE
Suggestion: A configurable max distance between nation and towns that can be invited

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2612]

**Comment by LlmDl** [comment]
0.91.4.8

```
    - New Config Option: Nation's require towns to be within X townblocks. 
      - Found in the config at global_town_settings.nation_requires_proximity
      - Default: 0.0
      - If greater than zero, towns must have their homeblock within that many or less townblocks from the nation's capital's homeblock to join. 
      - If greater than zero, towns must have their homeblocks in the same world as the nation to join.
```

**Comment by KarlOfDuty** [comment]
Is it possible to make it invitee town border to any nation town's border? It would make more sense as towns can then expand towards the nation, and maybe even require towns to be connected by borders to the rest of the nation. 

If only homeblocks matter you might be in a situation where you would have to claim a long line of plots toward a nation's capital and then set your homeblock at the end . This would be a pretty ugly solution for the players.

I of course see how this would be pretty bad for performance, so I suggest only checking for it when the invitee accepts the invite to reduce issues with invite spammers. 

I would also say that a bounding box for the town's territory would be ideal, letting the system only check against the four corners instead of every plot in one town vs every plot in all towns of the nation. It would only need to be updated on new claims.

Thoughts?
