### ISSUE TITLE
plot claim commands not working

### ISSUE THREAD

**Issue by pikachu99** [LlmDl/Towny#2620]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1./plot claim

### What is the expected output?
1."AN internal error occurred while attempting to perform this command"

### What is your Towny version?
Do not say "latest". 0.91.4.7

### What is your spigot/craftbukkit version?
Do not say "latest". Spigot

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/ahj9wtKy
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/dcFeT4Db
3. Your townyperms.yml : https://pastebin.com/KKbhd1RK
4. Your log's error : https://pastebin.com/ahj9wtKy

**Comment by LlmDl** [comment]
They're using /plot claim in a  townblock that belongs to the town because a mayor already used /t claim on it, right?

The log you linked isn't the startup, its just a whole bunch of plugins erroring. You probably need to get that sorted out. 

 Stop your server. Start your server, let it load completely, then stop it. A new latest.log will be created in your logs folder. Please upload it to http://pastie.org or http://pastebin.com and post the link here.

**Comment by pikachu99** [comment]
Sorry for late response I was busy with dealing with bad players. 
https://pastebin.com/hnNsw6m2

**Comment by LlmDl** [comment]
My guess is that your essentials' erroring all over the place is causing towny's reliance on its economy to not allow you to use /t claim. Solve the other plugins which are erroring and your towny will likely work. If this isn't the case, start a new ticket when your log has a clean startup.
