### ISSUE TITLE
Suggestion: Allow Auto-Unclaiming of excess chunks

### ISSUE THREAD

**Issue by CeilinCat** [LlmDl/Towny#2662]
Allow for it to be enabled in the config for excess chunks to be automatically unclaimed on new days.

Currently, towns can join Nations, claim all the town blocks they want and end up with 256/100 chunks, this causes issues for nations.

Unclaims most recently claimed chunks and then either reverts them if revert unclaims is enabled, and does not if revert unclaims is disabled.

**Comment by LlmDl** [comment]
We cannot tell how recent a chunk was claimed, we don't keep track of the date/time they're claimed.

How do you propose we decide which chunks to unclaim? Why not just charge an upkeep based on plot-claimed if people are abusing the nation system? Why not make it so that nations don't give so many bonus townblocks?

**Comment by LlmDl** [comment]
See as how there is no easy way to decide which townblocks would be unclaimed this is going to be closed.  Could be a better idea to ask for an additional upkeep cost paid against the number of plots above the townblock limit.
