### ISSUE TITLE
Server lag when player is killed in pvp combat

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2711]
This ticket template is for bug/error reports. If you are suggesting a feature and not reporting a bug please delete all the text here and begin your ticket Title with Suggestion:

### What steps will reproduce the problem?
1. Find a player to kill
2. Kill player
3. Server lags

### What is the expected output?
1. No lag
2.
3.

### What is your Towny version?
0.91.4.13

### What is your spigot/craftbukkit version?
git-Paper-1211 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://hastebin.com/cagijexora.md
2. Your Towny config.yml (if using MySQL please remove password,) : https://hastebin.com/ofedinowas.coffeescript
3. Your townyperms.yml :  https://hastebin.com/vozavobuca.vbs
4. Your log's error : No error

Youtube video: https://www.youtube.com/watch?v=NRQJZZNtSw8&feature=youtu.be

**Comment by LlmDl** [comment]
What makes you think this is Towny?

**Comment by KarlOfDuty** [comment]
Our performance monitor indicated it got stuck in a towny function for 3.6 seconds every time someone died but this was false. 

We were supposed to have all death prices off but had accidentally re-enabled it while copying some things from our beta-server config leading to the slowdowns. I only discovered it while double-checking the config right now.

You may close this issue as the slowdown was due to our economy plugin, not towny.
