### ISSUE TITLE
Suggestion: Improve invite system

### ISSUE THREAD

**Issue by Bezod** [LlmDl/Towny#2730]
Players should be prompted by towny to choose which town/nation to /accept if invited by more than one source. As of now players can only accept the last invite recieved.

**Comment by Wolf2323** [comment]
Also it would be nice when the player can klck in the chat on the message to accept an invitation.

**Comment by TheFlagCourier** [comment]
Sounds useful. Would definitely help on larger servers, and where new-member poaching is prevalent. To expand, you could execute it similar to below:

----

<SERVER> **You have been invited to _TownX_**.
Type or click on `/accept` to join the town.

<SERVER> **You have been invited to _TownY_.** 
You have multiple pending invitations. Click or Type `/invites` to see them.

\<User Input>: `/invites`

<SERVER> **Pending Invitations:**
(`/accept [townName]` , or _click on selection_)
1 - TownX - RefererX - Expiration: mm:ss
2 - TownY - RefererY - Expiration: mm:ss

----

I don't think using a single-digit ID is a good idea (ie: `/accept 1`), because if you use expirations, and ID 1 expires and is handed off to Invite 2, you can end up with players joining the wrong town. Might work where the ID is randomly generated.

**Comment by Articdive** [comment]
I think /accept {townname}, /decline (townname) first of all as a "has to"
Making these messages clickable, will requite use of the Spigot-API, also still possible and not problematic.
However giving each of these invites an int would be hard, we could in theory however make some sort of ( /town invite add and /town invite revoke ) system and add invites like in factions, a mayor can invite and the invite is always valid until restart or the mayor revokes it.

**Comment by Bezod** [comment]
Sounds good. If invited by more than one town its name has to be specified after the accept command eg /accept towname.

**Comment by LlmDl** [comment]
So far this is what we're going to do in some of the first dev builds after the release of 0.92.0.0:

New commands:

- /invites,/invite,/towny invites (same command, all aliases)
  - Will show a user their invites.
  - Invites to a user will be stored in their residentname.txt file
  - A user can have up to 8-9 invites (# determined by how many can be listed in one page)
  - sub commands:
    - accept (single invite)
    - accept {townname}
    - deny {townname}
    - deny all

- /town invite {resident} - will be an alias for /town add
- /town uninvite {resident} - withdraw an invite from a player
- /town invites - Might be added, would list invites out to players.

/accept and /deny will probably still function when there is a single invite given to a user.

**Comment by Bezod** [comment]
Nice!

**Comment by Wolf2323** [comment]
This changes are nice 👍 . But no Clickable messages 👎

**Comment by Articdive** [comment]
Actually clickable Messages would be able to be turned off and not really hard at all to do in this case afaik

**Comment by Lenti99** [comment]
Hello, I just wanted to add something on this. Maybe you could have a GUI where you can customize it. Basically, when someone invites you, you've got the option to say "Accept" or "Decline" through a GUI. This would make it easier for new players and such things. 

Thanks

**Comment by Articdive** [comment]
@Lenti99 Towny doesn't really work with GUIs you can get addons, GUIs wouldn't really work any better though, making 1 thing use an API and everything else not just doesn't fit, also there will probably be a TownyGUI addon which will add this

**Comment by LlmDl** [comment]
0.92.0.5 Has this great new system
