### ISSUE TITLE
[Suggestion] Worldguard Hook for region/towny priority

### ISSUE THREAD

**Issue by Jwguy0** [LlmDl/Towny#2741]
Is it possible to add a hook for Worldguard to establish priority for Towny permissions over Worldguard regions? If so, I'd like to sincerely request it be added.

We've been looking into ways to make the following diagram possible on our server, but so far it's been rather difficult because the two plugins don't want to work together, and they're both very popular and commonly used plugins:

![wg-towny](https://user-images.githubusercontent.com/33167263/33436874-dbc996cc-d5ab-11e7-9ece-d16a05f32f74.jpg)

Worldguard can be found here, and is well-documented for it's age: https://dev.bukkit.org/projects/worldguard

**Comment by LlmDl** [comment]
We won't be integrating WG, sorry. The area in red, is it meant to be Wilderness or a town?

**Comment by Jwguy0** [comment]
It's meant to be a region where building is not allowed, but building in towns are.

That's really unfortunate.

**Comment by LlmDl** [comment]
The only way I can see you managing it is the following, which doesn't require worldguard at all, just a lot of patience/claiming.

Instead of the blue area being protect by WG, claim it as a town and open all the plot permissions, using /t set perm on. This will make it a place anyone can build/destroy and so on, and it won't be claimable by other towns. Before you start claiming the blue area make sure that the revert on unclaim feature is turned off in the /tw panel, otherwise all the revert snapshots will slow down your load time. After it's claimed you can turn the feature back on if you wish.

The red area is the wilderness, which you can disallow build/destroy in, except the parts that get claimed by towns of course.
