### ISSUE TITLE
Item duplication on wild_revert_on_mob_explosion

### ISSUE THREAD

**Issue by Wolf2323** [LlmDl/Towny#2742]
### What steps will reproduce the problem?
1. Place a (non solid?) Block like a Torch, Pressureplate,Bed,...
2. Let a Creeper explode in the radius of the blocks
3. Now the Torch, Pressureplate,Bed,... drops but they also get regenerated

### What is the expected output?
1. No duplication of items so:
     - Let them drop and not regenerate or
     - Not drop and regenerate

### What is your Towny version?
0.91.4.16

### What is your spigot/craftbukkit version?
Spigot 1.12.2 git-Spigot-5695bca-53fccdf

**Comment by LlmDl** [comment]
This one has been reported before, if I recall correctly, there was no way to handle it properly because its not the explosion destroying the torch/pressureplate, it is actually falling off the wall/block from teh block breaking first. I couldn't find a good way to handle those torches/pressureplates/etc but since those items are fairly cheap I just let it go.

**Comment by Wolf2323** [comment]
I look a little bit if i can find a solution for this but you right that this is hard to handle.

**Comment by LlmDl** [comment]
I've done a partial fix included in 0.91.4.17, roughly half of the dupes don't drop now. The dupes are still caused by the attached blocks (torches, plates, etc,) that are breaking when the block they are stuck on explodes but are not actually being exploded themselves.

**Comment by LlmDl** [comment]
If you want to look over where I've just made my latest commit you can take a crack at it.

It would require looking at blockbreakevents, but I doubt you'd be able to see the cause of the event clear enough to know if it was caused by an attached-to-block exploding.
