### ISSUE TITLE
Hanging caused by towny commands?

### ISSUE THREAD

**Issue by monochrome-blue** [LlmDl/Towny#2803]
### What steps will reproduce the problem?
1. Using town commands results in a slight delay before a response; in this case, caused server to hang for a while
(This crash can't be reproduced 100% through these steps), I'm not exactly sure what caused it, but the town deposit seems the most likely cause. Error in logs (from VentureChat plugin) seems to be a result of the hanging

### What is the expected output?
1. $1 Being deposited into the town, "Losers"

### What is your Towny version?
Towny version 0.92.0.2

### What is your spigot/craftbukkit version?
paperspigot version git-paper-1310

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/A9nFst04
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jfcG9XZr
3. Your townyperms.yml : https://pastebin.com/WbrhUiJd
4. Your log's error :  https://pastebin.com/EvFuwkwF

If this is to do with chat,
Chat channels are managed by VentureChat (plugin which threw an error in console)

**Comment by LlmDl** [comment]
This is usually due to the economy plugin responding slowly to bank inquiries made by Towny. I've usually seen this with physical economies because the eco plugin has to go figure out what amount is sitting in a bank's chest somewhere. SaneEconomy is probably just being slow. We've already compensated for most of these command occaissions (/res /t /n) by doing the lookups in async tasks so there isn't anything that can be done on Towny's end to make it any faster for you, sorry.
