### ISSUE TITLE
publish towny for premium on spigot

### ISSUE THREAD

**Issue by jordanwilliams1** [LlmDl/Towny#2846]
Codding towny must be a hard job. Why don't you publish towny on spigot as a premium? Or even do what McMMO Did? Where you get the free version and buy the premium one on spigot as a donation. 

I Run a towny server myself and i wouldn't mind paying for towny if you did want to go fully premium with no free version. I Think it would be worth it for the devs of towny To give them back something.

McMMO Premium "Donation": https://www.spigotmc.org/resources/mcmmo.2445/

**Comment by LlmDl** [comment]
You're jordan who runs DifferentCraft, you violate the Towny license by selling Towny townblocks. I've asked you to stop selling those townblocks. Considering your server has already made more than $1500.00 this month in 'donations' I think you can probably do just fine without selling Towny townblocks.

Selling Towny on spigot would also be in violation of the Towny license, so that will not be happening.

I do not code Towny to make money, I do it as a hobby. The more I have to deal with servers that are in violation of the Towny license for selling townblocks, the more likely it will be I remove the ability to sell townblocks altogether.

**Comment by jordanwilliams1** [comment]
@LlmDl Sorry to disappoint you but advertising costs around $5-6k which we are currently saving for. I Can not code so most donations go into paying for devs. If you'd like to code for the server, Feel free

**Comment by jordanwilliams1** [comment]
@LlmDl Also, The server hardly ever sells them, Its mostly bought in-game with points that people get from voting.

**Comment by LlmDl** [comment]
@jordanwilliams1 then you should have no issue taking it off of your shop, right? Towny is not for commercial purposes.

**Comment by jordanwilliams1** [comment]
@LlmDl People want more stuff. We've had staff meetings and we've been asked to add more stuff. We are not going to remove things from the store that are available on the competition servers. I Completely understand what you're saying. I'm sorry.

**Comment by jordanwilliams1** [comment]
@LlmDl At least we aren't doing shit like this:
http://donate.maestrea.com/category/954376

That is disgusting in my eyes.
